// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SystemKadrowy.Infrastructure.Persistence;

#nullable disable

namespace SystemKadrowy.Infrastructure.Migrations
{
    [DbContext(typeof(KadryDbContext))]
    [Migration("20260106165525_RozbudowaDanychPracownika")]
    partial class RozbudowaDanychPracownika
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SystemKadrowy.Core.Domain.Adres", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("KodPocztowyId")
                        .HasColumnType("int");

                    b.Property<string>("NumerDomu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumerLokalu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ulica")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KodPocztowyId");

                    b.ToTable("Adresy");
                });

            modelBuilder.Entity("SystemKadrowy.Core.Domain.KodPocztowy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Miejscowosc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("KodyPocztowe");
                });

            modelBuilder.Entity("SystemKadrowy.Core.Domain.Nieobecnosc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataDo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataOd")
                        .HasColumnType("datetime2");

                    b.Property<int>("LiczbaDniRoboczych")
                        .HasColumnType("int");

                    b.Property<decimal>("LiczbaGodzin")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("PracownikId")
                        .HasColumnType("int");

                    b.Property<int>("Typ")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PracownikId");

                    b.ToTable("Nieobecnosci");
                });

            modelBuilder.Entity("SystemKadrowy.Core.Domain.Pracownik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AdresId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataUrodzenia")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumerKontaBankowego")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PESEL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZdjecieSciezka")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AdresId");

                    b.ToTable("Pracownicy");
                });

            modelBuilder.Entity("SystemKadrowy.Core.Domain.Umowa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CzyDobrowolneChorobowe")
                        .HasColumnType("bit");

                    b.Property<bool>("CzyKosztyPodwyzszone")
                        .HasColumnType("bit");

                    b.Property<bool>("CzyStudent")
                        .HasColumnType("bit");

                    b.Property<bool>("CzyUlgaPodatkowa")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataRozpoczecia")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataZakonczenia")
                        .HasColumnType("datetime2");

                    b.Property<int>("PracownikId")
                        .HasColumnType("int");

                    b.Property<int>("SposobWynagradzania")
                        .HasColumnType("int");

                    b.Property<string>("Stanowisko")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("StawkaBrutto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TypUmowy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PracownikId");

                    b.ToTable("Umowy");
                });

            modelBuilder.Entity("SystemKadrowy.Core.Domain.Wyplata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Brutto")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("DataGenerowania")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DoWyplaty")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("IleDniNieobecnosci")
                        .HasColumnType("int");

                    b.Property<decimal>("IleGodzinNieobecnosci")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("KosztyUzyskania")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("Miesiac")
                        .HasColumnType("int");

                    b.Property<decimal>("Netto")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Podatek")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("PotraceniaKomornicze")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("PotracenieZaNieobecnosci")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("PracownikId")
                        .HasColumnType("int");

                    b.Property<decimal>("PremiaBrutto")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("PrzepracowaneGodziny")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("Rok")
                        .HasColumnType("int");

                    b.Property<decimal>("SkladkaZdrowotna")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("WynagrodzenieChorobowe")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("ZUS_Razem")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("PracownikId");

                    b.ToTable("Wyplaty");
                });

            modelBuilder.Entity("SystemKadrowy.Core.Domain.Adres", b =>
                {
                    b.HasOne("SystemKadrowy.Core.Domain.KodPocztowy", "KodPocztowy")
                        .WithMany("Adresy")
                        .HasForeignKey("KodPocztowyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KodPocztowy");
                });

            modelBuilder.Entity("SystemKadrowy.Core.Domain.Nieobecnosc", b =>
                {
                    b.HasOne("SystemKadrowy.Core.Domain.Pracownik", "Pracownik")
                        .WithMany("Nieobecnosci")
                        .HasForeignKey("PracownikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pracownik");
                });

            modelBuilder.Entity("SystemKadrowy.Core.Domain.Pracownik", b =>
                {
                    b.HasOne("SystemKadrowy.Core.Domain.Adres", "AdresZamieszkania")
                        .WithMany()
                        .HasForeignKey("AdresId");

                    b.Navigation("AdresZamieszkania");
                });

            modelBuilder.Entity("SystemKadrowy.Core.Domain.Umowa", b =>
                {
                    b.HasOne("SystemKadrowy.Core.Domain.Pracownik", "Pracownik")
                        .WithMany("Umowy")
                        .HasForeignKey("PracownikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pracownik");
                });

            modelBuilder.Entity("SystemKadrowy.Core.Domain.Wyplata", b =>
                {
                    b.HasOne("SystemKadrowy.Core.Domain.Pracownik", "Pracownik")
                        .WithMany("Wyplaty")
                        .HasForeignKey("PracownikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pracownik");
                });

            modelBuilder.Entity("SystemKadrowy.Core.Domain.KodPocztowy", b =>
                {
                    b.Navigation("Adresy");
                });

            modelBuilder.Entity("SystemKadrowy.Core.Domain.Pracownik", b =>
                {
                    b.Navigation("Nieobecnosci");

                    b.Navigation("Umowy");

                    b.Navigation("Wyplaty");
                });
#pragma warning restore 612, 618
        }
    }
}
